### ISSUE TITLE
[common] helm-doc odd behaviour for first Item in list/dictionary

### ISSUE THREAD

**Issue by TobyTheHutt** [bedag/helm-charts#107]
**Describe the bug**
When documentation is provided for a key which happens to be the first object of a dictionary entry, `helm-doc` will document the object as `parentItem[0]`. Example from the common Chart:

``` yaml
# -- ingress is used for access from outside of kubernetes
ingress:
  # -- rules is a list of host rules used to configure the Ingress
  rules:
    # -- host is the URL which ingress is listening
    - host: myapp.cluster.local
```

... will result in the following documentation:

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| ingress.rules | list | `[{"host":"myapp.cluster.local","http":{"paths":[{"backend":{"serviceNameSuffix":"component-1","servicePort":"http"},"path":"/","pathType":"ImplementationSpecific"}]}}]` | rules is a list of host rules used to configure the Ingress |
| ingress.rules[0] | object | `{"host":"myapp.cluster.local","http":{"paths":[{"backend":{"serviceNameSuffix":"component-1","servicePort":"http"},"path":"/","pathType":"ImplementationSpecific"}]}}` | host is the URL which ingress is listening |

**Version of Helm and Kubernetes**:

**Helm Version**: `v3.12.0`
**Kubernetes Version**: `1.27`

**Which chart**:

`[bedag/common]`

**What happened**:

While working on the `common` chart, I noticed that certain keys in the documentation don't get properly displayed, because their position is also the start of a dictionary entry.

**What you expected to happen**:

I would expect the keys to be documented by their proper name.

**How to reproduce it** (as minimally and precisely as possible):

1. go to the `values.yaml` in the `bedag/common` chart
2. see the `ingress` section, specifically the `$ingress.rules.host` key
3. look up the key documentation in the README.md under `ingress.rules[0]`
4. to verify the behaviour, run another `make helm-doc`

**Anything else we need to know**:

No
