### ISSUE TITLE
[manifests] bundle resource names are not respected in secretKeyRef

### ISSUE THREAD

**Issue by brjos** [bedag/helm-charts#27]
**Describe the bug**
When defining a `name` in the bundle.yaml for statefulsets or deployments, and when adding secret env vars in these statefulsets or deployments, the given name is not being used in the secretKeyRef which leads to an error.

**Version of Helm and Kubernetes**:

**Helm Version**: `v3.4.2`
**Kubernetes Version**: `1.19.6`

**Which chart**:

`[bedag/manifests]`

**What happened**:
Wrong secret name in secretKeyRef of the pods spec.containers.env

**What you expected to happen**:
correct secret name to be used in secretKeyRef

**How to reproduce it** (as minimally and precisely as possible):
lets say in the bundle we have something like
```
  - type: "statefulset"
    values: {{ toYaml $.Values.myapp.statefulset | nindent 6 }}
    name: myapp
```

in the values we have:
```
myapp:
  statefulset:
    environment:
      - name: MY_SECRET
        value: "donttell"
        secret: true
```

Then we deploy this in a release called "bla", this leads to a `CreateContainerConfigError` status of the pod, because in the pods spec.containers.env theres is the wrong secret name being used:
```
    - name: MY_SECRET
      valueFrom:
        secretKeyRef:
          key: MY_SECRET
          name: bla-fullname-env
```

Instead of the fullname, the `name` given in the bundle should be used (if one is set)

**Comment by oliverbaehler** [comment]
@brjos I was able to reproduce it. I opened a Merge Request resolving the issue (in my opinion). I assigned you as reviewer - before merge - test if it resolves your issue. Here my test values/output:

**Bundle.yaml**

```
{{- include "bedag-lib.manifest.bundle" (dict "bundle" (fromYaml (include "test.bundle" $)) "context" $) | nindent 0 }}

{{- define "test.bundle" -}}
resources:
  - type: "deployment"
    fullname: "customName"
    overwrites:
      environment:
        - name: "secret1"
          secret: true
          value: "secret1"
        - name: "secret2"
          secret: true
          value: "secret2"
        - name: "test1"
          value: "value1"
        - name: "test2"
          value: "value2"
{{- end }}

```

**Output**

``` 
# Source: test/templates/bundle.yaml
apiVersion: v1
kind: Secret
metadata:
  name: customname-env
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.16.0
type: Opaque
data:
  secret1: c2VjcmV0MQ==
  secret2: c2VjcmV0Mg==
---
# Source: test/templates/bundle.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: customname
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/name: test
    app.kubernetes.io/version: 1.16.0
spec:
  replicas: 1
  selector:
    matchLabels:
      
      app.kubernetes.io/name: test
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/name: test
    spec:
      serviceAccountName: default
      containers:
        -
          name: test
          image: docker.io/bitnami/apache:1.16.0
          imagePullPolicy: 
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

           ## Important Part

            - name: "secret1"
              valueFrom:
                secretKeyRef:
                  name: customname-env
                  key: "secret1"
            - name: "secret2"
              valueFrom:
                secretKeyRef:
                  name: customname-env
                  key: "secret2"
            - name: test1
              value: value1
            - name: test2
              value: value2
```
